### ISSUE TITLE
[Bug]: prettier --write error

### ISSUE THREAD

**Issue by Michael-py001** [lzm0x219/template-vite-react#685]
### Describe the bug

1. When I run `git commit` , something wrong with `prettier --write error` and `Command "lint-staged" not found`

### To Reproduce

  1. git add .
  2. git commit -m 'init'
  3. See error

### Expected behavior

no errors

### Screenshots

![image](https://github.com/lzm0x219/template-vite-react/assets/60598432/911fc5cf-ca21-48fc-b960-116238f768c0)

**Comment by lzm0x219** [comment]
thanks, I'll check right away.

**Comment by lzm0x219** [comment]
Is there any installation project dependency?

**Comment by lzm0x219** [comment]
I can't reproduce it

**Comment by Michael-py001** [comment]
I copied the template again, and everything run with no errors.  I think it's my computer's problem probably.😥
